In [10]:
import pandas as pd
df = pd.read_csv('complaints.csv')

https://www.kaggle.com/vineetverma/clustering-bank-complaints

In [13]:
original = df

In [12]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2019-05-28,"Credit reporting, credit repair services, or o...",Credit reporting,Problem with a credit reporting company's inve...,Their investigation did not fix an error on yo...,Although I am checking for and addressing miss...,NaN,"EQUIFAX, INC.",GA,310XX,NaN,Consent provided,Web,2019-05-28,Closed with explanation,Yes,NaN,3255189
1,2019-09-24,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,transworld systems inc. \nis trying to collect...,NaN,TRANSWORLD SYSTEMS INC,FL,335XX,NaN,Consent provided,Web,2019-09-24,Closed with explanation,Yes,NaN,3384392
2,2019-09-19,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PA,15206,NaN,Consent not provided,Web,2019-09-20,Closed with non-monetary relief,Yes,NaN,3379500
3,2019-11-08,Debt collection,I do not know,Communication tactics,Frequent or repeated calls,"Over the past 2 weeks, I have been receiving e...",NaN,"Diversified Consultants, Inc.",NC,275XX,NaN,Consent provided,Web,2019-11-08,Closed with explanation,Yes,NaN,3433198
4,2019-05-03,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Account information incorrect,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",OK,735XX,NaN,NaN,Referral,2019-05-03,Closed with explanation,Yes,NaN,3231144

In [14]:
df = df[['Consumer complaint narrative','Product']]
df.shape

(1761388, 2)

In [33]:
df.groupby('Product').size().sort_values(ascending=False)

Product
Credit reporting, credit repair services, or other personal consumer reports    203735
Debt collection                                                                 122018
Mortgage                                                                         68825
Credit card or prepaid card                                                      42475
Credit reporting                                                                 31588
Student loan                                                                     26885
Checking or savings account                                                      24687
Credit card                                                                      18838
Bank account or service                                                          14885
Money transfer, virtual currency, or money service                               10653
Vehicle loan or lease                                                            10322
Consumer Loan                                                                     9473
Payday loan, title loan, or personal loan                                         7968
Payday loan                                                                       1746
Money transfers                                                                   1497
Prepaid card                                                                      1450
Other financial service                                                            292
Virtual currency                                                                    16
dtype: int64

In [15]:
df.head()

,Consumer complaint narrative,Product
0,Although I am checking for and addressing miss...,"Credit reporting, credit repair services, or o..."
1,transworld systems inc. \nis trying to collect...,Debt collection
2,NaN,"Credit reporting, credit repair services, or o..."
3,"Over the past 2 weeks, I have been receiving e...",Debt collection
4,NaN,"Credit reporting, credit repair services, or o..."

In [16]:
df = df[df["Consumer complaint narrative"].notnull() == True]

In [17]:
df.shape

(597353, 2)

In [18]:
df["category_id"] = df["Product"].factorize()[0]

In [19]:
df

,Consumer complaint narrative,Product,category_id
0,Although I am checking for and addressing miss...,"Credit reporting, credit repair services, or o...",0
1,transworld systems inc. \nis trying to collect...,Debt collection,1
3,"Over the past 2 weeks, I have been receiving e...",Debt collection,1
5,"In XX/XX/2018, I discovered that my ex husband...","Credit reporting, credit repair services, or o...",0
6,"Previously, on XX/XX/XXXX, XX/XX/XXXX, and XX/...","Credit reporting, credit repair services, or o...",0
...,...,...,...
1761383,I recieved a collections call from an unknown ...,Debt collection,1
1761384,"On XXXX XXXX, 2015, I contacted XXXX XXXX, who...",Mortgage,5
1761385,I made a payment to CITI XXXX Credit Card on X...,Credit card,8
1761386,cfbp i would Like to file a complaint on Exper...,Credit reporting,12
1761387,My husband and I are in the middle of an FHA S...,Credit reporting,12

In [20]:
df['Product'].unique()

array(['Credit reporting, credit repair services, or other personal consumer reports',
       'Debt collection', 'Student loan',
       'Money transfer, virtual currency, or money service',
       'Vehicle loan or lease', 'Mortgage', 'Checking or savings account',
       'Credit card or prepaid card', 'Credit card',
       'Payday loan, title loan, or personal loan', 'Consumer Loan',
       'Payday loan', 'Credit reporting', 'Other financial service',
       'Bank account or service', 'Money transfers', 'Prepaid card',
       'Virtual currency'], dtype=object)

In [21]:
category_id_df = df[['Product', 'category_id']].drop_duplicates().sort_values('category_id')
category_id_df

                                                  Product  category_id
0       Credit reporting, credit repair services, or o...            0
1                                         Debt collection            1
15                                           Student loan            2
20      Money transfer, virtual currency, or money ser...            3
25                                  Vehicle loan or lease            4
27                                               Mortgage            5
28                            Checking or savings account            6
88                            Credit card or prepaid card            7
249                                           Credit card            8
355             Payday loan, title loan, or personal loan            9
970                                         Consumer Loan           10
4141                                          Payday loan           11
56683                                    Credit reporting           12
85997                             Other financial service           13
104941                            Bank account or service           14
152828                                    Money transfers           15
251947                                       Prepaid card           16
598714                                   Virtual currency           17

In [22]:
category_to_id = dict(category_id_df.values)
id_to_category = dict(category_id_df[['category_id', 'Product']].values)

In [24]:
category_to_id

{'Credit reporting, credit repair services, or other personal consumer reports': 0,
 'Debt collection': 1,
 'Student loan': 2,
 'Money transfer, virtual currency, or money service': 3,
 'Vehicle loan or lease': 4,
 'Mortgage': 5,
 'Checking or savings account': 6,
 'Credit card or prepaid card': 7,
 'Credit card': 8,
 'Payday loan, title loan, or personal loan': 9,
 'Consumer Loan': 10,
 'Payday loan': 11,
 'Credit reporting': 12,
 'Other financial service': 13,
 'Bank account or service': 14,
 'Money transfers': 15,
 'Prepaid card': 16,
 'Virtual currency': 17}